goog.provide('zombie.scene.props');
zombie.scene.props.powerup = (function zombie$scene$props$powerup(database,id,p__10627){
var map__10628 = p__10627;
var map__10628__$1 = cljs.core.__destructure_map(map__10628);
var initial_position = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__10628__$1,new cljs.core.Keyword(null,"initial-position","initial-position",1055724056));
var name = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__10628__$1,new cljs.core.Keyword(null,"name","name",1843675177));
var modifier = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__10628__$1,new cljs.core.Keyword(null,"modifier","modifier",1634442788));
var jitter = Math.random();
return (function (){
var t = Math.sin((2.0 * (jitter + cljs.core.deref((function (){var G__10629 = zombie.state.databases.game;
var G__10630 = new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"time","time",1385887882)], null);
return (threeagent.core.cursor.cljs$core$IFn$_invoke$arity$2 ? threeagent.core.cursor.cljs$core$IFn$_invoke$arity$2(G__10629,G__10630) : threeagent.core.cursor.call(null,G__10629,G__10630));
})()))));
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"object","object",1474613949),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"id","id",-1388402092),id,new cljs.core.Keyword(null,"physics","physics",-1254209137),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"parts","parts",849007691),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"hull","hull",-957096876),new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"type","type",1174270348),new cljs.core.Keyword(null,"rectangle","rectangle",293163262),new cljs.core.Keyword(null,"width","width",-384071477),0.5,new cljs.core.Keyword(null,"height","height",1025178622),0.5,new cljs.core.Keyword(null,"settings","settings",1556144875),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"isSensor","isSensor",734841684),true,new cljs.core.Keyword(null,"isStatic","isStatic",1002568003),true,new cljs.core.Keyword(null,"collisionFilter","collisionFilter",-161885110),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"category","category",-593092832),zombie.util.common.physics_layer_props,new cljs.core.Keyword(null,"mask","mask",-585748447),zombie.util.common.physics_layer_player], null)], null),new cljs.core.Keyword(null,"on-collision-start","on-collision-start",1608797537),(function (){
cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$variadic(zombie.state.databases.player,cljs.core.update_in,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"modifiers","modifiers",50378834),new cljs.core.Keyword(null,"stat","stat",-1370599836).cljs$core$IFn$_invoke$arity$1(modifier)], null),cljs.core.conj,cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"amount","amount",364489504).cljs$core$IFn$_invoke$arity$1(modifier)], 0));

return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$3(database,cljs.core.dissoc,id);
})], null)], null)], null),new cljs.core.Keyword(null,"position","position",-2011731912),initial_position], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"object","object",1474613949),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(0),((t + 1.5) / 2.0),(0)], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"box","box",1530920394),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"material","material",460118677),new cljs.core.Keyword("material","powerup-blue","material/powerup-blue",-1491870893).cljs$core$IFn$_invoke$arity$1(cljs.core.deref(zombie.state.databases.assets)),new cljs.core.Keyword(null,"scale","scale",-230427353),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [0.5,0.5,0.5], null),new cljs.core.Keyword(null,"rotation","rotation",-1728051644),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(0),t,(0)], null)], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"text","text",-1790561697),new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"text","text",-1790561697),name,new cljs.core.Keyword(null,"anchor-x","anchor-x",-1597588837),"center",new cljs.core.Keyword(null,"scale","scale",-230427353),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(5),(5),(5)], null),new cljs.core.Keyword(null,"rotation","rotation",-1728051644),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(0),zombie.util.math.pi4,(0)], null),new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(0),(1),(0)], null)], null)], null)], null)], null);
});
});

//# sourceMappingURL=zombie.scene.props.js.map
